### ISSUE TITLE
Ubuntu

### ISSUE THREAD

**Issue by denis-vk** [brichard19/BitCrack#35]
How compille and run on Ubuntu 16.04. Help me please

**Comment by brichard19** [comment]
Hi,

Make sure you have the CUDA Toolkit 9.2 installed [https://developer.nvidia.com/cuda-downloads](https://developer.nvidia.com/cuda-downloads)

To compile on Ubuntu, run `make`.

The binaries will be in the `bin` directory

Let me know if you need help.

Thanks

**Comment by ogronome** [comment]
In Arch linux it doesn't compile as well.

cuda 9.2.148-2 is installed
gcc7 7.3.1+20180814-1 by dependancy for cuda

after trying to make I get several errors about ambiguity like

KeyFinder.cpp: In member function ‘void KeyFinder::generateStartingPoints()’:
KeyFinder.cpp:244:37: error: call of overloaded ‘add(uint64_t&)’ is ambiguous
   _exponents.push_back(privKey.add(i));
                                     ^
In file included from /tmp/BitCrack/cudaDeviceContext/DeviceContext.h:6:0,
                 from /tmp/BitCrack/cudaDeviceContext/CudaDeviceContext.h:4,
                 from KeyFinder.cpp:4:

**Comment by brichard19** [comment]
Linux build is fixed now.

Thanks

**Comment by denis-vk** [comment]
ptxas /tmp/tmpxft_00012b43_00000000-6_atomiclist.ptx, line 49; error   : Call has wrong number of parameters
ptxas /tmp/tmpxft_00012b43_00000000-6_atomiclist.ptx, line 75; error   : Call has wrong number of parameters
ptxas fatal   : Ptx assembly aborted due to errors
Makefile:8: recipe for target 'cuda' failed
make[1]: *** [cuda] Error 255
make[1]: Leaving directory '/home/ubuntu/BitCrack/KeyFinderLib'
Makefile:50: recipe for target 'dir_keyfinderlib' failed
make: *** [dir_keyfinderlib] Error 2

**Comment by brichard19** [comment]
Hi,

In `Makefile`, try changing `COMPUTE_CAP` to `70`.

Let me know if that works.

Thanks

**Comment by ogronome** [comment]
Thank's! Now it compiles at least in Arch. And after correcting COMPUTE_CAP even works :)

**Comment by natedawg469** [comment]
If there is any space at the beginning or end of the address in the text file, it will render unrecoqnizable like it did for you. Theres a typo error in your file, check it.

**Comment by denis-vk** [comment]
No mistakes!
On Windows it works!

**Comment by nightwalker89** [comment]
Maybe the new line char is different. Try to make new list in Linux.

**Comment by brichard19** [comment]
Hi,

This is due to Linux leaving the carriage return in the buffer when reading lines (I'm guessing you made the file in Windows?). I have fixed the code to remove it when reading addresses.

Try pulling the latest code.

Thanks

**Comment by denis-vk** [comment]
Hello, yes, it's all right.
I now have a new question. Is it possible to change the code in this way, the -s flag was automatically selected at startup? not with 1, as it is now

I think that it is necessary for someone and in windows

**Comment by JakinH** [comment]
![image](https://user-images.githubusercontent.com/43468687/45874012-6a6bf880-bd59-11e8-8d90-7386ac4356d7.png)
I've used COMPUTE_CAP 30 and 70 as suggested above.  Still getting invalid device symbol error.

Suggestions?

**Comment by brichard19** [comment]
Glad you were able to figure it out!

**Comment by jamesyoungdigital** [comment]
Can someone help with a build on Ubuntu 16.04 LTS using CUDA 9.2?

When I type "make" I get a lib directory, but no bin directory, and no binaries.  Is anyone else having this same problem?

**Comment by brichard19** [comment]
Try `make BUILD_OPENCL=1` or `make BUILD_CUDA=1`

I'll fix the make script to catch that.

**Comment by mirameshs** [comment]
I am trying to compile on ubuntu 22.04 .
there is no file to run after make or sudo make
