### ISSUE TITLE
program exit

### ISSUE THREAD

**Issue by josefelip** [brichard19/BitCrack#7]
the program exit and end when I load 2999 address from file, work good if load 2500 addresses:

C:\Users\Jose\Downloads\BitCrack-master\x64\Release2>BitCrack64 -i addresstemp.txt -c -u
Device:      GeForce GT 740M
Targets:     2999
Compression: both
Starting at: 0000000000000000000000000000000000000000000000000000000000000001
Initializing...
C:\Users\Jose\Downloads\BitCrack-master\x64\Release2>

**Comment by brichard19** [comment]
Hi there,

This is fixed in the latest release.

Thanks

**Comment by josefelip** [comment]
the problem persist when Targets are >13000 : (option default compressed, both and uncompressed)

test1:
C:\Users\user1\Desktop\BitCrack-master292\BitCrack-master\x64\Release>BitCrack64 -i Addresstop.txt -s 0000000000000000000000000000000000000000000000000000000000000001 -o res.txt
Device:      GeForce GTX 1050 Ti
Targets:     13050
Compression: compressed
Starting at: 0000000000000000000000000000000000000000000000000000000000000001
Initializing...
C:\Users\user1\Desktop\BitCrack-master292\BitCrack-master\x64\Release>

test2:
C:\Users\user1\Desktop\BitCrack-master292\BitCrack-master\x64\Release>BitCrack64 -i Addresstop.txt -c -u -s 0000000000000000000000000000000000000000000000000000000000000001 -o res.txt
Device:      GeForce GTX 1050 Ti
Targets:     13050
Compression: both
Starting at: 0000000000000000000000000000000000000000000000000000000000000001
Initializing...
C:\Users\user1\Desktop\BitCrack-master292\BitCrack-master\x64\Release>

test3:
C:\Users\Jose\Downloads\BitCrack-master\x64\Release29>BitCrack64 -i Addresstop.txt -s 0000000000000000000000000000000000000000000000000000000000000001 -o res.txt
Device:      GeForce GT 740M
Targets:     13050
Compression: compressed
Starting at: 0000000000000000000000000000000000000000000000000000000000000001
0.93 MKey/s (7,340,032 total) [00:00:05]
C:\Users\Jose\Downloads\BitCrack-master\x64\Release29>
^^^^end program

**Comment by josefelip** [comment]
hi, good job,

please update github o send me code modification where 40,000 addresses
work ok. thanks

i am investing for security in blockchain, your program is very important
for this.

email me: josefelip@gmail.com
i make now a donation en ETH ;)

**Comment by josefelip** [comment]
hi, i would like load big numbers of Targets, but i have error.

please send me line code of increase the bloom buffer or patch, thanks.
note:  GeForce GTX 1050 Ti has 4gb ram, system have 16gb

BitCrack64 -i Addresstop.txt -c -u -s
0000000000000000000000000000000000000000000000000000000000000001 -o res.txt
Device:      GeForce GTX 1050 Ti
Targets:     2099553
Compression: both
Starting at:
0000000000000000000000000000000000000000000000000000000000000001
3.51 MKey/s (1,294,467,072 total) [00:06:09]Error: Device error: out of
memory

**Comment by brichard19** [comment]
Hi there,

Dynamic bloom filter sizing is implemented. This is my device with 5 million addresses:

BitCrack64.exe -i 5m.txt
Compression: compressed
Starting at: 0000000000000000000000000000000000000000000000000000000000000001
GeForce GT 640   342/1024MB | 5042424 targets 8.17 MKey/s (253,493,248 total) [00:00:29]
